FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["echo-cs.csproj", "./"]
RUN dotnet restore "echo-cs.csproj"
COPY . .
#WORKDIR "/src"
RUN dotnet build "echo-cs.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "echo-cs.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "echo-cs.dll"]