# A YAML file containing information about the chart
# https://docs.helm.sh/developing_charts/#charts


apiVersion: v1 # The chart API version, always "v1" (required)
# appVersion: "1.0" # The version of the app that this contains - not part of the operative version, just an option of arbitary versioning format (optional). 
version: 0.1.1 # A semantic version (required) // https://semver.org/
description: Ping/Pong Helm chart for Kubernetes
name: ping-pong-chart # The name should match the folder (required)
keywords: # A list of keywords about this project (optional)
  - bnaya
  - istio
  - helm
  - sample
# kubeVersion: # A SemVer range of compatible Kubernetes versions (optional)
home: https://medium.com/@bnayae/ # The URL of this project's home page (optional)
sources: # A list of URLs to source code for this project (optional)
  - https://github.com/bnayae/istio-playground

maintainers: # (optional)
  - name: bnaya # The maintainer's name (required for each maintainer)
    # email: # The maintainer's email (optional for each maintainer)
    url: https://twitter.com/bnayae?lang=en # A URL for the maintainer (optional for each maintainer)

# engine: gotpl # The name of the template engine (optional, defaults to gotpl)
icon: https://raw.githubusercontent.com/bnayae/BeyondAsyncAwait/master/20.%20Cool%20Extensions/async-ex.png # A URL to an SVG or PNG image to be used as an icon (optional).
# deprecated: Whether this chart is deprecated (optional, boolean)
# tillerVersion: The version of Tiller that this chart requires. This should be expressed as a SemVer range: ">2.0.0" (optional)