FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY ["ping-cs.csproj", "./"]
RUN dotnet restore "ping-cs.csproj"
COPY . .
Run echo --------------------------------------------------
RUN dotnet build "ping-cs.csproj" -c Release -o /app
Run echo ==================================================

FROM build AS publish
RUN dotnet publish "ping-cs.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "ping-cs.dll"]